### ISSUE TITLE
Design Brief

### ISSUE THREAD

**Issue by lshoffman1** [Chicago/design.chicago.gov#35]

**Comment by taitcha** [comment]
A design brief establishes clear expectations between a business and the designer. A design brief template cannot be a ‘one size fits all’ because design projects vary so much, ranging from product innovation and improvement, to service delivery, software development and graphic design. Use this template as a starting point and modify as necessary. When you have finished delete the blue instructional text.
Business name: (Insert Business name here)
Client contact: (Insert client contact name here)
Contact number: (Insert contact number here)

Due date for completion: (if you have any dependencies which make a particular start and end date critical make sure you communicate these before you brief a designer. You may need to negotiate with the designer depending on how in-demand they are and the complexity of the project. The due date for completion is when you expect to have the final, approved design in your hand, ready for use.)
Review date/s: (there should be at least one client review to ensure the design meets client expectations. You can also use this section to specify completion dates of other key stages.)
Budget: (provide an idea of how much money you plan to spend. This enables the designer to be realistic when they provide options.)
Product/service/brand name: (aim to reflect the purpose of the design project in its title. If it’s in the public domain title may need to include branding.)
Key objectives: (main business benefits of getting this design successfully delivered.)
Marketing objectives and target audience: (detailed description of the target market and marketing approach. Include details such as occupation, gender ratio, average age, nationality/location, psychological demographic, lifestyle preferences, advertising and promotional plans, distribution etc.)

Regulatory issues: (note any regulations which will impact the design e.g. product labelling laws.)
Scope: (detailed list of everything this project is expected to deliver.)
Not in scope: (use this section to specify design elements that are out of scope e.g. if you're completing a web design project but don’t want an email newsletter.)
Purpose and function: (use this section if you are briefing a product designer. To be able to provide a workable design, the designer needs to know what the product is supposed to be able to do, who will be using it and in what circumstances. This information may be obvious to the inventor but still needs to be spelled out clearly for the designer.) 
Format: (use this section if you are briefing a graphic designer. Depending on how you plan to use the design(s) specify if it is for print or web, file format, file size, resolution or other attributes. For printed items tell the designer about the stock you plan to use as factors such as absorbency can affect the final result and therefore the designer's approach.)
Design Project plan: (list the project milestones, what is needed to complete them and who is responsible.)
Attachments: (provide anything you want to use e.g. existing logos, sketches of prototypes, examples of designs or products (as benchmarks or comparison), or competitors you need to stand out from. Ask the designer to specify requirements such as minimum resolutions for samples to be used in the final design.)
Measures of success: (how will you ensure the design is appropriate for your objectives and audience e.g. will you show samples to your potential customers, run surveys etc.)

**Comment by dekdekdek** [comment]
@taitcha where's the source? this is great explanation.

**Comment by dekdekdek** [comment]
https://www.canva.com/learn/effective-design-brief/
